### ISSUE TITLE
Personal project? Or module?

### ISSUE THREAD

**Issue by Monte9** [Piroro-hs/react-native-twitter#1]
Hi! I am looking to implement Twitter login for my app and I was wondering this is your personal project or are you trying to build a Twitter login wrapper that others can use? 

Something similar to this? https://github.com/magus/react-native-facebook-login

Let me know. 
Thanks.

**Comment by Piroro-hs** [comment]
I'm trying to build a library for the Twitter API and my main purpose is to make use of streaming APIs. 
For Twitter login, maybe you can use [this](https://www.npmjs.com/package/react-native-twitter-signin) or [that](https://www.npmjs.com/package/react-native-social-auth)?

Thanks.
