### ISSUE TITLE
Sources for assign MUST be an object

### ISSUE THREAD

**Issue by KeanuTomatoMomotaro** [Piroro-hs/react-native-twitter#13]
I'm getting a problem after attempting to invoke the rest.post() method to tweet some text.

The code for the method is 
`postTweet(){
      var tokens= {
        consumer_key:         'xxx',
        consumer_secret:      'xxx',
        access_token:         'xxx',
        access_token_secret:  'xxx',              
      };
      const {rest} = twitter(tokens);
     var path = 'statuses/update';
      var params = this.state.text;
      rest.post(path , params)
      .then(() => {console.log('Posted');})
      .catch(console.error);
    }`

![image](https://user-images.githubusercontent.com/23183047/32939790-3ca6038e-cbb3-11e7-8b15-aab6f07771d0.png)

**Comment by Piroro-hs** [comment]
`params` should be an `Object`. Try `rest.post('statuses/update', {status: this.state.text})`.
See [Twitter docs](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update#parameters) for more info.

**Comment by KeanuTomatoMomotaro** [comment]
@Piroro-hs tx, its not returning the same error now, but a new error with code 32 (cant authenticate you). Is this caused by my tokens and access keys?
