### ISSUE TITLE
POST request giving Error 220 Your credentials do not allow access to this resource

### ISSUE THREAD

**Issue by selimonline** [Piroro-hs/react-native-twitter#19]
Dear,

I want to send direct msg to followers. I have enabled permission in twitter apps management end.  Here is my code

```
const {rest, stream} = twitter(tokens);

        rest.post('direct_messages/new', [{
            screen_name:'username',
            user_id:'2761567848',
            text:'this is test message'
        }]).then(function(data){
            console.log(data);
        });

```
Error: 220 Your credentials do not allow access to this resource.

can idea pls? Can u give me any working example of post?

**Comment by EnesBildiren** [comment]
@salimbutex please check your mail box
