### ISSUE TITLE
iOS Example

### ISSUE THREAD

**Issue by masiamj** [Piroro-hs/react-native-twitter#5]
Is this project specific to Android? If not, can you please update the example project to include an iOS example?

I've integrated the library but having real trouble getting the access tokens when the Promise resolves.

Thanks!

**Comment by kyle-ssg** [comment]
@masiamj did you come up with a solution for this ?

**Comment by kyle-ssg** [comment]
Right, so I did in fact get it to work : I'd advise adding this to the example. If you did too it would have been good if you'd have posted a solution.

It's actually pretty easy to get this to work for iOS with a few modifications of AppDelegate


```
#import <React/RCTLinkingManager.h>

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options{
        ... other url logic such as facebook/google 
        return [RCTLinkingManager application:application openURL:url options:options];
}

````
