### ISSUE TITLE
Not able to retweet

### ISSUE THREAD

**Issue by vijayst** [Piroro-hs/react-native-twitter#7]
I am using `client.rest.post('statuses/retweet/:id', { id })` to retweet. But I get an error saying: No status found with { id: 0 }.

**Comment by vijayst** [comment]
Closing this issue - as it seems to work fine after I reinstalled.

**Comment by vijayst** [comment]
It is still happening for me. It worked for a few times. And then stopped working. 
![screenshot_20170825-165528](https://user-images.githubusercontent.com/3457565/29712242-8a3f5a62-89b6-11e7-84d9-8f87be9c65e7.jpg)

**Comment by Piroro-hs** [comment]
Maybe you use `Number` as `id`. JavaScript cannot support numbers with > 53-bits, so `id` should be `String`.

**Comment by vijayst** [comment]
Thanks, using id_str instead of id worked.
